-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.temperature
(
    id integer,
    dev_id text NOT NULL,
    accquisition_time timestamp with time zone,
    backend_timestamp time with time zone NOT NULL,
    celsius numeric NOT NULL,
    additions text[],
    PRIMARY KEY (id)
);

COMMENT ON TABLE public.temperature
    IS 'Database for holding all the data from the sensor systems';

CREATE TABLE IF NOT EXISTS public.sensor
(
    dev_id text,
    type integer NOT NULL,
    description text,
    soc numeric,
    battery_voltage numeric,
    latitude numeric,
    longitude numeric,
    additions_description text[],
    PRIMARY KEY (dev_id)
);

COMMENT ON TABLE public.sensor
    IS 'Description for the sensors';

CREATE TABLE IF NOT EXISTS public.gps
(
    id integer,
    dev_id text NOT NULL,
    accquisition_time timestamp with time zone,
    backend_timestamp time with time zone NOT NULL,
    latitude numeric NOT NULL,
    longitude numeric NOT NULL,
    kmh numeric,
    degrees numeric,
    altitude numeric,
    additions text[],
    PRIMARY KEY (id)
);

COMMENT ON TABLE public.gps
    IS 'Database for holding all the data from the sensor systems';

CREATE TABLE IF NOT EXISTS public.level
(
    id integer,
    dev_id text NOT NULL,
    accquisition_time timestamp with time zone,
    backend_timestamp time with time zone NOT NULL,
    meter numeric NOT NULL,
    additions text[],
    PRIMARY KEY (id)
);

COMMENT ON TABLE public.level
    IS 'Database for holding all the data from the sensor systems';

ALTER TABLE IF EXISTS public.temperature
    ADD CONSTRAINT dev_id FOREIGN KEY (dev_id)
    REFERENCES public.sensor (dev_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.gps
    ADD CONSTRAINT dev_id FOREIGN KEY (dev_id)
    REFERENCES public.sensor (dev_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.level
    ADD FOREIGN KEY (dev_id)
    REFERENCES public.sensor (dev_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;